import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import minioConfig from '@config/minio.config';
import { MinioService } from '@infrastructure/storage/minio.service';
import { PublicCmsController, InternalCmsController } from './controllers';
import {
  GetPostCategoriesUseCase,
  GetPostCategoryByIdUseCase,
  CreatePostCategoryUseCase,
  UpdatePostCategoryUseCase,
  TogglePostCategoryUseCase,
  DeletePostCategoryUseCase,
  GetCmsPagesUseCase,
  GetCmsPageBySlugUseCase,
  GetCmsPageByIdUseCase,
  CreateCmsPageUseCase,
  UpdateCmsPageUseCase,
  PublishCmsPageUseCase,
  GetPublishedBlogPostsUseCase,
  GetBlogPostBySlugUseCase,
  GetBlogPostsUseCase,
  GetBlogPostByIdUseCase,
  CreateBlogPostUseCase,
  UpdateBlogPostUseCase,
  PublishBlogPostUseCase,
  ToggleBlogPostFeaturedUseCase,
  DeleteBlogPostUseCase,
  GetActiveEventsUseCase,
  GetEventByIdPublicUseCase,
  GetEventsUseCase,
  GetEventByIdUseCase,
  CreateEventUseCase,
  UpdateEventUseCase,
  ToggleEventFeaturedUseCase,
  DeleteEventUseCase,
  GetMediaFilesUseCase,
  GetMediaFileByIdUseCase,
  CreateMediaFileUseCase,
  UpdateMediaFileUseCase,
  DeleteMediaFileUseCase,
  UploadMediaUseCase,
  STORAGE_SERVICE_TOKEN,
} from '@application/cms/use-cases/cms.use-cases';
import {
  PostCategoryAdapter,
  CmsPageAdapter,
  BlogPostAdapter,
  EventAdapter,
  MediaFileAdapter,
} from '@infrastructure/prisma/repositories/cms/cms.adapter';
import {
  POST_CATEGORY_REPOSITORY_TOKEN,
  CMS_PAGE_REPOSITORY_TOKEN,
  BLOG_POST_REPOSITORY_TOKEN,
  EVENT_REPOSITORY_TOKEN,
  MEDIA_FILE_REPOSITORY_TOKEN,
} from '@domain/cms/ports/cms.repository.token';

@Module({
  imports: [ConfigModule.forFeature(minioConfig)],
  controllers: [PublicCmsController, InternalCmsController],
  providers: [
    MinioService,
    { provide: STORAGE_SERVICE_TOKEN, useExisting: MinioService },
    // Repository tokens → adapters
    { provide: POST_CATEGORY_REPOSITORY_TOKEN, useClass: PostCategoryAdapter },
    { provide: CMS_PAGE_REPOSITORY_TOKEN, useClass: CmsPageAdapter },
    { provide: BLOG_POST_REPOSITORY_TOKEN, useClass: BlogPostAdapter },
    { provide: EVENT_REPOSITORY_TOKEN, useClass: EventAdapter },
    { provide: MEDIA_FILE_REPOSITORY_TOKEN, useClass: MediaFileAdapter },
    // Post Category Use Cases
    GetPostCategoriesUseCase,
    GetPostCategoryByIdUseCase,
    CreatePostCategoryUseCase,
    UpdatePostCategoryUseCase,
    TogglePostCategoryUseCase,
    DeletePostCategoryUseCase,
    // CMS Page Use Cases
    GetCmsPagesUseCase,
    GetCmsPageBySlugUseCase,
    GetCmsPageByIdUseCase,
    CreateCmsPageUseCase,
    UpdateCmsPageUseCase,
    PublishCmsPageUseCase,
    // Blog Post Use Cases
    GetPublishedBlogPostsUseCase,
    GetBlogPostBySlugUseCase,
    GetBlogPostsUseCase,
    GetBlogPostByIdUseCase,
    CreateBlogPostUseCase,
    UpdateBlogPostUseCase,
    PublishBlogPostUseCase,
    ToggleBlogPostFeaturedUseCase,
    DeleteBlogPostUseCase,
    // Event Use Cases
    GetActiveEventsUseCase,
    GetEventByIdPublicUseCase,
    GetEventsUseCase,
    GetEventByIdUseCase,
    CreateEventUseCase,
    UpdateEventUseCase,
    ToggleEventFeaturedUseCase,
    DeleteEventUseCase,
    // Media File Use Cases
    GetMediaFilesUseCase,
    GetMediaFileByIdUseCase,
    CreateMediaFileUseCase,
    UpdateMediaFileUseCase,
    DeleteMediaFileUseCase,
    UploadMediaUseCase,
  ],
  exports: [
    POST_CATEGORY_REPOSITORY_TOKEN,
    CMS_PAGE_REPOSITORY_TOKEN,
    BLOG_POST_REPOSITORY_TOKEN,
    EVENT_REPOSITORY_TOKEN,
    MEDIA_FILE_REPOSITORY_TOKEN,
  ],
})
export class CmsModule {}
