export const CMS_PAGE_REPOSITORY_TOKEN = Symbol('CMS_PAGE_REPOSITORY');
export const BLOG_POST_REPOSITORY_TOKEN = Symbol('BLOG_POST_REPOSITORY');
export const EVENT_REPOSITORY_TOKEN = Symbol('EVENT_REPOSITORY');
export const MEDIA_FILE_REPOSITORY_TOKEN = Symbol('MEDIA_FILE_REPOSITORY');
