export const MENU_CATEGORY_REPOSITORY_TOKEN = Symbol('MENU_CATEGORY_REPOSITORY');
export const MENU_ITEM_REPOSITORY_TOKEN = Symbol('MENU_ITEM_REPOSITORY');
export const MENU_ITEM_PRICE_REPOSITORY_TOKEN = Symbol('MENU_ITEM_PRICE_REPOSITORY');
